language: cpp
compiler:
  - clang

os: osx

before_script:
  - export PATH=$HOME/Library/Python/2.7/bin:$PATH
  - echo $PATH
  - pip install --user cpp-coveralls


script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . -j 4

after_success:
  - coveralls
  - cpp-coveralls