language: cpp
compiler:
  - clang

os: osx

before_script:
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . -j 4

after_success:
  - coveralls
  - cpp-coveralls